# Generated by Django 4.2.6 on 2025-02-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='photo',
            field=models.ImageField(blank=True, default='stock_images/default.png', null=True, upload_to='stock_images'),
        ),
    ]
